language: java
before_install: echo $HOME

script:
  - echo "skipping tests"

before_deploy:
  - npm install
  - git submodule init
  - git submodule update
  - (cd igpop && make build)
  - java -jar "./igpop/target/igpop.jar" build "/ig-ae"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master